image_config: &image_config

  # make sure to set your Docker Hub username and password in CircleCI, either in this project's environment variables or in your organization's org-global Context

  IMAGE_NAME: # name your image
  
  IMAGE_VERSION: # pick a version number for your image
  
  LINUX_VERSION: # options: DEBIAN_JESSIE, DEBIAN_STRETCH, UBUNTU_TRUSTY, UBUNTU_XENIAL
  
  RUBY_VERSION: # select a version number from https://cache.ruby-lang.org/pub/ruby
  
  NODE_VERSION: # select a version number from https://nodejs.org/dist
  
  PYTHON_VERSION: # select a version number  from https://python.org/ftp/python
  
  JAVA: # options: true, false
  
  MYSQL_CLIENT: # options: true, false
    
  POSTGRES_CLIENT: # options: true, false

version: 2
jobs:
  build:
    machine: true
    environment:
      <<: *image_config
        
    steps:
      - checkout
      
##      - run: bash generate.sh > Dockerfile
      
##      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      
##      - run: docker build -t $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_VERSION .
      
##      - run: docker push $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_VERSION
      
##  test_image:
##    docker:
##      - image: $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_VERSION
      
##    steps:
      
##      - checkout
      
##workflows:
##  version: 2
##  dockerfile_wizard:
##    jobs:
##      - build:
##          context: org-global
          
##      - test_image:
##          requires:
##            - build