image_config: &image_config

  # make sure to set your Docker Hub username and password in CircleCI, either as project-specific environment variables or as resources in your organization's org-global Context

  IMAGE_NAME: test
  
  IMAGE_VERSION: v1
  
  LINUX_VERSION: UBUNTU_TRUSTY
  
  RUBY_VERSION: 2.3.4
  
  NODE_VERSION: 6.11.3
  
  PYTHON_VERSION: 2.7.13
  
  JAVA: true
  
  MYSQL_CLIENT: true
    
  POSTGRES_CLIENT: true

version: 2
jobs:
  build:
    machine: true
    environment:
      <<: *image_config
        
    steps:
      - checkout
      
      - run: bash generate.sh > Dockerfile
      
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      
      - run: docker build -t $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_VERSION .
      
      - run: docker push $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_VERSION
      
  test_image:
    docker:
      - image: $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_VERSION
      
    steps:
      
      - checkout
      
workflows:
  version: 2
  dockerfile_wizard:
    jobs:
      - build:
          context: org-global
          
      - test_image:
          requires:
            - build