image_config: &image_config

  # make sure to set your Docker Hub username and password in CircleCI, either as project-specific environment variables or as resources in your organization's org-global Context

  IMAGE_NAME: ksjdf
  
  IMAGE_VERSION: 4
  
  # NOTE: if you're modifying this config.yml file manually rather than using the included setup script, make sure you also add your IMAGE_NAME and IMAGE_VERSION to the `test_image` job (line 45)
  
  LINUX_VERSION: DEBIAN_STRETCH
  
  
  
  
  
  
  
  JAVA: true
  
  MYSQL_CLIENT: false
    
  POSTGRES_CLIENT: false

version: 2
jobs:
  build:
    machine: true
    environment:
      <<: *image_config
        
    steps:
      - checkout
      
      - run: bash generate.sh > Dockerfile
      
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      
      - run: echo $RUBY_VERSION
      - run: echo "$RUBY_VERSION"
      
      - run: docker build -t $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_VERSION .
      
      - run: docker push $DOCKER_USERNAME/$IMAGE_NAME:$IMAGE_VERSION
      
  test_image:
    docker:
      - image: $DOCKER_USERNAME/ksjdf:4
      
    steps:
      
      - checkout

      - run: lsb_release -a
      - run: node --version
      - run: ruby --version
      - run: python --version
      - run: java -version
      - run: mysql --version
      - run: psql --version
      
workflows:
  version: 2
  dockerfile_wizard:
    jobs:
      - build:
          context: org-global
          
      - test_image:
          context: org-global
          requires:
            - build